#!/bin/bash

APPLETVIEWER=appletviewer

jvmtype=${2-"jdk"}

case $jvmtype in
    jdk)
    echo "sun jdk"
    LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/progs/javalibs $APPLETVIEWER $1
    ;;
    kaffelocal)
    echo `/usr/local/kaffe/bin/kaffe -version`
    /usr/local/kaffe/bin/kaffe -classpath /usr/local/kaffe/jre/lib/rt.jar:ShareDraw.jar  kaffe.applet.AppletViewer $1
    ;;
    *)
    echo "other"
    ;;
esac

