#!/bin/bash

source ./project_params

drawserver=$1
if test -z $drawserver
then
    drawserver=127.0.0.1
fi

JARPROG=dist/lib/sharedrawweb-${project_version}.jar

#LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/progs/javalib/
java -jar $JARPROG -Djava.security.policy=java.policy $project_mainclass $drawserver

