#!/bin/sh

drawserver=$1
if test -z $drawserver
then
    drawserver=127.0.0.1
fi

JARPROG=dist/lib/sharedrawweb-0.0.1.jar
MAINCLASS=lasnier.sharedraw.ShareDrawServer

#LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/progs/javalib/
java -jar $JARPROG -Djava.security.policy=java.policy $MAINCLASS $drawserver

